{% set name = "varlink" %}
{% set version = "30.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f51a88197ded3de10dafdf6f7bb3f4d88216b8f068d78e7f0818a3fa71589c86

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - future  # [py27]
    - pip
    - python
  run:
    - future  # [py27]
    - python

test:
  imports:
    - varlink

about:
  home: "https://github.com/varlink/python"
  license: "Apache Software"
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "Varlink"
  doc_url: "https://varlink.github.io/python/"
  dev_url: "https://github.com/varlink/python/"

extra:
  recipe-maintainers:
    - h-vetinari
    - "4383"
