{% set version = "30.3.1" %}

package:
  name: varlink
  version: {{ version }}

source:
  url: https://github.com/varlink/python/archive/{{ version }}.tar.gz
  sha256: 0fd82802fb56a2964a8c3a322c58724ef4767a77c49c2bcca51bd96cddfdf791
  patches:
    - patches/0001-remove-setuptools-requirement-from-setup.cfg.patch

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - varlink

about:
  home: https://github.com/varlink/python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Varlink
  doc_url: https://varlink.github.io/python/
  dev_url: https://github.com/varlink/python/

extra:
  recipe-maintainers:
    - h-vetinari
    - '4383'
