{% set version = "31.0.0" %}

package:
  name: varlink
  version: {{ version }}

source:
  url: https://github.com/varlink/python/archive/{{ version }}.tar.gz
  sha256: 3c1f0ef71d887717e890a195811569535991863fa21da0c23c176d58f1732ebe

build:
  number: 3
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION="$PKG_VERSION"  # [not win]
    - set SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%      # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - setuptools_scm
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - varlink

about:
  home: https://github.com/varlink/python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Varlink
  doc_url: https://varlink.github.io/python/
  dev_url: https://github.com/varlink/python/

extra:
  recipe-maintainers:
    - h-vetinari
    - '4383'
