travis:
  secure:
    BINSTAR_TOKEN: BLQ4G+gNReu8IqBQ0skB909BxG4DAxswVo57S8A6ifXHyz1jBW1Tn1lbYIpFBXHit8NmO8XWnGO4GWoeH/OEz6qBe6snW5njldFogrLn1lmNtfsXIiYHGyqKFumC2Zc3kwt3AOP6RZuIUBuAaBOob7b5aD9u6zs1kk9uPXt9QHUng+0KBLqyqChnqo+flqKsOkQJqLnqRynTUOYnISH7x0GxscJkGKboW7nBOuVdmloAaPcJxJLStniCNa0I4X6ancTXDU6fiVidNG1PYlnqHsL0dYdWe41sfF97aQ3cpjuViACyA+lbhoXfgkEw3RdDWYUfvUV92d8HP4meQUHvPCESfczzLUeNKZ4wmpiASdYQFF7OIWLjmiZrMQSPIdF4UM8VMkYcdFGVjtCo8gf/iG3Vx/6hbItzqoHgWiluqNtGdNBOVuTltbjhlg0zmvb+TNptrO6LLgzs+AUpiHgFHdXOkxuyNfVh6M2FCS4scQuoaQfs30rVNh8rR0TnPPuila5ZNU+al5dSmbv6V+xHPJVOW9Ll81fYFwK+IKHoUfTq3Evwo17LzW0F2Nt5C7Rvz5N84uVm779jbV+xB62MbfF+0/+uLm5UDm7V3Pjh3m6xKQPrQ2foatkR09IkHEuwNkRbxhd4our/ZRv2AcQP3AuqbT6eKUZSGA1i8QYZ5Xs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
